=== chapel-lang/chapel/third-party/hwloc/hwloc-src/hwloc/hwloc2.dtd
<!--
  Copyright © 2009      CNRS
  Copyright © 2009-2021 Inria.  All rights reserved.
  Copyright © 2009-2011 Université Bordeaux.
  See COPYING in top-level directory.

  This is the DTD for hwloc v2.x XMLs.
 -->

<!ELEMENT topology (object+,distances2*,distances2hetero*,support*,memattr*,cpukind*)>
<!ATTLIST topology version CDATA "">

<!ELEMENT object (page_type*,info*,userdata*,object*)>
<!ATTLIST object type (Machine | Misc | Group | NUMANode | MemCache | Package | Die | L1Cache | L2Cache | L3Cache | L4Cache | L5Cache | L1iCache | L2iCache | L3iCache | Core | PU | Bridge | PCIDev | OSDev) #REQUIRED>
<!ATTLIST object subtype CDATA "" >
<!ATTLIST object os_index CDATA "-1" >
<!ATTLIST object gp_index CDATA "-1" >
<!ATTLIST object name CDATA "" >
<!ATTLIST object local_memory CDATA "0" >
<!ATTLIST object cache_size CDATA "0" >
<!ATTLIST object cache_linesize CDATA "0" >
<!ATTLIST object cache_associativity CDATA "0" >
<!ATTLIST object cache_type CDATA "0" >
<!ATTLIST object cpuset CDATA "0" >
<!ATTLIST object complete_cpuset CDATA "" >
<!ATTLIST object allowed_cpuset CDATA "" >
<!ATTLIST object nodeset CDATA "" >
<!ATTLIST object complete_nodeset CDATA "" >
<!ATTLIST object allowed_nodeset CDATA "" >
<!ATTLIST object depth CDATA "-1" >
<!ATTLIST object kind CDATA "0" >
<!ATTLIST object subkind CDATA "0" >
<!ATTLIST object dont_merge CDATA "0" >
<!ATTLIST object bridge_type CDATA "" >
<!ATTLIST object bridge_pci CDATA "" >
<!ATTLIST object pci_busid CDATA "" >
<!ATTLIST object pci_type CDATA "" >
<!ATTLIST object pci_link_speed CDATA "0." >
<!ATTLIST object osdev_type CDATA "" >

<!ELEMENT page_type EMPTY>
<!ATTLIST page_type size CDATA #REQUIRED>
<!ATTLIST page_type count CDATA #REQUIRED>

<!ELEMENT info EMPTY>
<!ATTLIST info name CDATA #REQUIRED>
<!ATTLIST info value CDATA #REQUIRED>

<!ELEMENT distances2 (indexes+,u64values+)>
<!ATTLIST distances2 type CDATA #REQUIRED>
<!ATTLIST distances2 nbobjs CDATA #REQUIRED>
<!ATTLIST distances2 indexing CDATA #REQUIRED>
<!ATTLIST distances2 kind CDATA #REQUIRED>
<!ATTLIST distances2 name CDATA "">

<!ELEMENT distances2hetero (indexes+,u64values+)>
<!ATTLIST distances2hetero nbobjs CDATA #REQUIRED>
<!ATTLIST distances2hetero kind CDATA #REQUIRED>
<!ATTLIST distances2hetero name CDATA "">

<!ELEMENT memattr (memattr_value*)>
<!ATTLIST memattr name CDATA #REQUIRED>
<!ATTLIST memattr flags CDATA #REQUIRED>

<!ELEMENT memattr_value EMPTY>
<!ATTLIST memattr_value target_obj_gp_index CDATA "">
<!ATTLIST memattr_value target_obj_type CDATA #REQUIRED>
<!ATTLIST memattr_value value CDATA #REQUIRED>
<!ATTLIST memattr_value initiator_cpuset CDATA "">
<!ATTLIST memattr_value initiator_obj_gp_index CDATA "">
<!ATTLIST memattr_value initiator_obj_type CDATA "">

<!ELEMENT indexes (#PCDATA)>
<!ATTLIST indexes length CDATA #REQUIRED>

<!ELEMENT u64values (#PCDATA)>
<!ATTLIST u64values length CDATA #REQUIRED>

<!ELEMENT userdata (#PCDATA)>
<!ATTLIST userdata name CDATA "" >
<!ATTLIST userdata length CDATA "0" >
<!ATTLIST userdata encoding CDATA "" >

<!ELEMENT support EMPTY>
<!ATTLIST support name CDATA #REQUIRED>
<!ATTLIST support value CDATA "1" >

<!ELEMENT cpukind (info*)>
<!ATTLIST cpukind cpuset CDATA "0">
<!ATTLIST cpukind forced_efficiency CDATA "-1">

=== chapel-lang/chapel/third-party/hwloc/hwloc-src/tests/hwloc/xml/fakecpukinds.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" allowed_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" allowed_nodeset="0x00000001" gp_index="1">
    <info name="Backend" value="x86"/>
    <object type="Package" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2">
      <object type="NUMANode" os_index="0" cpuset="0x0000000f" complete_cpuset="0x0000000f" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3"/>
      <object type="Core" os_index="0" cpuset="0x00000005" complete_cpuset="0x00000005" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4">
        <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5"/>
        <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="6"/>
      </object>
      <object type="Core" os_index="1" cpuset="0x0000000a" complete_cpuset="0x0000000a" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="7">
        <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="8"/>
        <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="9"/>
      </object>
    </object>
  </object>
  <support name="discovery.cpukind_efficiency"/>
  <support name="custom.exported_support"/>
  <cpukind cpuset="0x00000003" forced_efficiency="0">
    <info name="CoreType" value="MySmallCore"/>
    <info name="FrequencyMaxMHz" value="1000"/>
  </cpukind>
  <cpukind cpuset="0x00000004" forced_efficiency="7">
    <info name="CoreType" value="YouBigcore"/>
    <info name="FrequencyMaxMHz" value="2000"/>
  </cpukind>
  <cpukind cpuset="0x00000008" forced_efficiency="10">
    <info name="CoreType" value="IntelCore"/>
    <info name="FrequencyMaxMHz" value="2000"/>
    <info name="Features" value="EverythingAndEvenMore"/>
  </cpukind>
</topology>

=== chapel-lang/chapel/third-party/hwloc/hwloc-src/tests/hwloc/xml/8intel64-4n2t-memattrs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x000000ff" complete_cpuset="0x000000ff" allowed_cpuset="0x000000ff" nodeset="0x0000000f" complete_nodeset="0x0000000f" allowed_nodeset="0x0000000f" gp_index="1">
    <info name="Backend" value="Synthetic"/>
    <info name="SyntheticDescription" value="node:4 pu:2"/>
    <info name="hwlocVersion" value="2.2.0a1-git"/>
    <info name="ProcessName" value="memattrs"/>
    <object type="Group" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="5" kind="1001" subkind="0">
      <object type="NUMANode" os_index="0" cpuset="0x00000003" complete_cpuset="0x00000003" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="4" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2"/>
      <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="3"/>
    </object>
    <object type="Group" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="9" kind="1001" subkind="0">
      <object type="NUMANode" os_index="1" cpuset="0x0000000c" complete_cpuset="0x0000000c" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="8" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="6"/>
      <object type="PU" os_index="3" cpuset="0x00000008" complete_cpuset="0x00000008" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="7"/>
    </object>
    <object type="Group" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="13" kind="1001" subkind="0">
      <object type="NUMANode" os_index="2" cpuset="0x00000030" complete_cpuset="0x00000030" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="12" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="PU" os_index="4" cpuset="0x00000010" complete_cpuset="0x00000010" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="10"/>
      <object type="PU" os_index="5" cpuset="0x00000020" complete_cpuset="0x00000020" nodeset="0x00000004" complete_nodeset="0x00000004" gp_index="11"/>
    </object>
    <object type="Group" cpuset="0x000000c0" complete_cpuset="0x000000c0" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="17" kind="1001" subkind="0">
      <object type="NUMANode" os_index="3" cpuset="0x000000c0" complete_cpuset="0x000000c0" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="16" local_memory="1073741824">
        <page_type size="4096" count="262144"/>
      </object>
      <object type="PU" os_index="6" cpuset="0x00000040" complete_cpuset="0x00000040" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="14"/>
      <object type="PU" os_index="7" cpuset="0x00000080" complete_cpuset="0x00000080" nodeset="0x00000008" complete_nodeset="0x00000008" gp_index="15"/>
    </object>
  </object>
  <support name="custom.exported_support"/>
  <memattr name="Bandwidth" flags="5">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="20" initiator_cpuset="0x000000ff"/>
  </memattr>
  <memattr name="foobar" flags="6">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="2345" initiator_obj_gp_index="15" initiator_obj_type="PU"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="10" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="20" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="30" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="123" initiator_cpuset="0x00000011"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="40" initiator_cpuset="0x00000003"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="2345" initiator_cpuset="0x00000011"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="23456" initiator_cpuset="0x00000012"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="23456" initiator_obj_gp_index="13" initiator_obj_type="Group"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="789" initiator_obj_gp_index="12" initiator_obj_type="NUMANode"/>
  </memattr>
  <memattr name="barnoinit" flags="1">
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="16" value="2345"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="4" value="10"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="8" value="2345"/>
    <memattr_value target_obj_type="NUMANode" target_obj_gp_index="12" value="23456"/>
    <memattr_value target_obj_type="PU" target_obj_gp_index="2" value="478945"/>
    <memattr_value target_obj_type="Group" target_obj_gp_index="17" value="789"/>
  </memattr>
  <memattr name="coincoin" flags="5"/>
</topology>

=== chapel-lang/chapel/third-party/hwloc/hwloc-src/tests/hwloc/xml/8intel64-fakeKNL-A2A-hybrid.rootattachednumas.v1tov2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topology SYSTEM "hwloc2.dtd">
<topology version="2.0">
  <object type="Machine" os_index="0" cpuset="0x00006000,,0x00040000,0x00006007" complete_cpuset="0x00006000,,0x00040000,0x00006007" allowed_cpuset="0x00006000,,0x00040000,0x00006007" nodeset="0x00000003" complete_nodeset="0x00000003" allowed_nodeset="0x00000003" gp_index="1">
    <info name="ClusterMode" value="All2All"/>
    <info name="MemoryMode" value="Hybrid50"/>
    <info name="DMIProductName" value="GROVEPORT"/>
    <info name="DMIProductVersion" value="E63448-400"/>
    <info name="DMIProductSerial" value="SPRO03200016"/>
    <info name="DMIProductUUID" value="FFFFFFFF-FFFF-0F08-0C09-290DFFFFFFFF"/>
    <info name="DMIBoardVendor" value="Intel Corp."/>
    <info name="DMIBoardName" value="GROVEPORT"/>
    <info name="DMIBoardVersion" value="E63448-400"/>
    <info name="DMIBoardSerial" value="SPRO03200016"/>
    <info name="DMIBoardAssetTag" value="Base Board Asset Tag"/>
    <info name="DMIChassisVendor" value="Intel Corporation"/>
    <info name="DMIChassisType" value="23"/>
    <info name="DMIChassisVersion" value="0.1"/>
    <info name="DMIChassisSerial" value="UNKNOWN"/>
    <info name="DMIChassisAssetTag" value="Chassis Asset Tag"/>
    <info name="DMIBIOSVendor" value="Intel Corporation"/>
    <info name="DMIBIOSVersion" value="GVPRCRB1.86B.0008.V70.1511250749"/>
    <info name="DMIBIOSDate" value="11/25/2015"/>
    <info name="DMISysVendor" value="Intel Corp."/>
    <info name="Backend" value="Linux"/>
    <info name="LinuxCgroup" value="/"/>
    <info name="OSName" value="Linux"/>
    <info name="OSRelease" value="3.10.0-327.el7.x86_64"/>
    <info name="OSVersion" value="#1 SMP Thu Oct 29 17:29:29 EDT 2015"/>
    <info name="HostName" value="gklab-119a-144"/>
    <info name="Architecture" value="x86_64"/>
    <info name="hwlocVersion" value="2.1.0a1-git"/>
    <info name="ProcessName" value="lstopo"/>
    <object type="NUMANode" os_index="0" cpuset="0x00006000,,0x00040000,0x00006007" complete_cpuset="0x00006000,,0x00040000,0x00006007" nodeset="0x00000001" complete_nodeset="0x00000001" gp_index="2" local_memory="51431501824">
      <page_type size="4096" count="12556519"/>
      <page_type size="2097152" count="0"/>
      <page_type size="1073741824" count="0"/>
    </object>
    <object type="NUMANode" os_index="1" cpuset="0x00006000,,0x00040000,0x00006007" complete_cpuset="0x00006000,,0x00040000,0x00006007" nodeset="0x00000002" complete_nodeset="0x00000002" gp_index="25" subtype="MCDRAM" local_memory="8589934592">
      <page_type size="4096" count="2097152"/>
      <page_type size="2097152" count="0"/>
      <page_type size="1073741824" count="0"/>
    </object>
    <object type="L2Cache" cpuset="0x00006000,,0x00040000,0x00000001" complete_cpuset="0x00006000,,0x00040000,0x00000001" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="3" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
      <object type="L1Cache" cpuset="0x00002000,,,0x00000001" complete_cpuset="0x00002000,,,0x00000001" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="4" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
        <object type="L1iCache" cpuset="0x00002000,,,0x00000001" complete_cpuset="0x00002000,,,0x00000001" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="5" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
          <object type="Core" os_index="0" cpuset="0x00002000,,,0x00000001" complete_cpuset="0x00002000,,,0x00000001" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="6">
            <object type="PU" os_index="0" cpuset="0x00000001" complete_cpuset="0x00000001" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="7"/>
            <object type="PU" os_index="109" cpuset="0x00002000,,,0x0" complete_cpuset="0x00002000,,,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="8"/>
          </object>
        </object>
      </object>
      <object type="L1Cache" cpuset="0x00004000,,0x00040000,0x0" complete_cpuset="0x00004000,,0x00040000,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="9" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
        <object type="L1iCache" cpuset="0x00004000,,0x00040000,0x0" complete_cpuset="0x00004000,,0x00040000,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="10" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
          <object type="Core" os_index="1" cpuset="0x00004000,,0x00040000,0x0" complete_cpuset="0x00004000,,0x00040000,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="11">
            <object type="PU" os_index="50" cpuset="0x00040000,0x0" complete_cpuset="0x00040000,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="12"/>
            <object type="PU" os_index="110" cpuset="0x00004000,,,0x0" complete_cpuset="0x00004000,,,0x0" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="13"/>
          </object>
        </object>
      </object>
    </object>
    <object type="L2Cache" cpuset="0x00006006" complete_cpuset="0x00006006" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="14" cache_size="1048576" depth="2" cache_linesize="64" cache_associativity="16" cache_type="0">
      <object type="L1Cache" cpuset="0x00002002" complete_cpuset="0x00002002" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="15" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
        <object type="L1iCache" cpuset="0x00002002" complete_cpuset="0x00002002" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="16" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
          <object type="Core" os_index="64" cpuset="0x00002002" complete_cpuset="0x00002002" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="17">
            <object type="PU" os_index="1" cpuset="0x00000002" complete_cpuset="0x00000002" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="18"/>
            <object type="PU" os_index="13" cpuset="0x00002000" complete_cpuset="0x00002000" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="19"/>
          </object>
        </object>
      </object>
      <object type="L1Cache" cpuset="0x00004004" complete_cpuset="0x00004004" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="20" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="1">
        <object type="L1iCache" cpuset="0x00004004" complete_cpuset="0x00004004" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="21" cache_size="32768" depth="1" cache_linesize="64" cache_associativity="8" cache_type="2">
          <object type="Core" os_index="65" cpuset="0x00004004" complete_cpuset="0x00004004" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="22">
            <object type="PU" os_index="2" cpuset="0x00000004" complete_cpuset="0x00000004" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="23"/>
            <object type="PU" os_index="14" cpuset="0x00004000" complete_cpuset="0x00004000" nodeset="0x00000003" complete_nodeset="0x00000003" gp_index="24"/>
          </object>
        </object>
      </object>
    </object>
  </object>
  <support name="custom.exported_support"/>
</topology>
